### ISSUE TITLE
After last update not working (Meteor 1.2.0.1)

### ISSUE THREAD

**Issue by cosio55** [francocatena/meteor-status#23]
Hi, I updated this package using 'meteor update' but now the package is not working, I am receiving this error on console: Uncaught ReferenceError: i18n_status_func is not defined

**Comment by miri-am** [comment]
same for me

**Comment by jasonxeno** [comment]
Breaks when minified, after typing "meteor --production"

**Comment by sferoze** [comment]
yup breaking in production for me too

**Comment by francocatena** [comment]
This is a duplicate of #22 if that doesn't fix your issue, please feel free to reopen it.

Cheers.
