### ISSUE TITLE
Clock discrepancy detected. Attempting re-sync.

### ISSUE THREAD

**Issue by aessig** [francocatena/meteor-status#29]
Hello, thank you very much for this great package !  I have this log all the time in my client’s console. Is there a way to mute clients logging in the package? The issue is known and come from setInterval, as mentioned [here](https://github.com/mizzao/meteor-timesync/issues/24).

**Comment by francocatena** [comment]
Hi @aessig,

Love to hear that you like the package.

That log appears only if you use `mizzao:timesync` (in fact, is done [here](https://github.com/mizzao/meteor-timesync/blob/master/timesync-client.js#L168)). If you want to mute it, I think the only option is to set `TimeSync.loggingEnabled` to `false` as suggested in the issue you pointed to.

Cheers.

**Comment by aessig** [comment]
Thanks 👍

**Comment by francocatena** [comment]
You're welcome =)

**Comment by anormore** [comment]
Sorry to re-open,

How can I hook in to this setting, and show users "Re-Syncing"?

I have a game (www.StarCommanderOnline.com), if users leave the tab open for a long time, it un-syncs. Right now I manually reload their page after 3 minutes of inactivity, and coming back to the tab.

But now I understand they are unsynced, how can I show an icon on their screen to say "We're re-syncing your client"?

**Comment by anormore** [comment]
SORRY nevermind, I'm here from a different package that uses this. Beautiful package, works great. Now users know what's going on with their connection. WONDERFUL. :) 👍
