### ISSUE TITLE
No styles (expecting bootstrap?)

### ISSUE THREAD

**Issue by Kestanous** [francocatena/meteor-status#6]
I am using Semantic-UI and the banner is quite barren. You don't specify any requirements but I am assuming you are expecting Bootstrap? would you mind adding css styles or dynamic templates?

**Comment by Kestanous** [comment]
I forked and cloned this to my app and changed the template to the following: 
```html
<template name="status">
  {{#unless connected}}
    <div class="ui negative message">
      <div class="content">
        <div class="header">
          {{message}}
        </div>
        <p>
          {{extraMessage}}
          {{#if showReconnect}}
            <a href="#" class="alert-link">{{reconnectLabel}}</a>
          {{/if}}
        </p>
      </div>
    </div>
  {{/unless}}
</template>
```
Which gives:
![my_bus_app](https://cloud.githubusercontent.com/assets/1283884/5812404/e1d69e7c-a037-11e4-9a67-0807f0b98089.png)

How would you like me to proceed?

**Comment by francocatena** [comment]
Hi @Kestanous, I just added some functionality, so now you can use your own template like this:

FIrst create you own template, naming it "status_semantic_ui"

```html
<template name="status_semantic_ui">
  {{#unless connected}}
    <div class="ui negative message">
      <div class="content">
        <div class="header">
          {{message}}
        </div>
        <p>
          {{extraMessage}}
          {{#if showReconnect}}
            <a href="#" class="alert-link">{{reconnectLabel}}</a>
          {{/if}}
        </p>
      </div>
    </div>
  {{/unless}}
</template>
```

And then add a line to your startup, setting the new template:

```javascript
Meteor.startup(function () {
  Status.setTemplate('semantic_ui')
})
```

It would be awesome if you can make a pull request and put your template in the `templates` folder. After that I explain this config in the README.

The release with template support is 1.0.4.

Cheers.

**Comment by Kestanous** [comment]
Thanks! I created that PR for you with some added fun #7
