### ISSUE TITLE
style for popup?

### ISSUE THREAD

**Issue by yuomtheara** [francocatena/meteor-status#9]
I would like to set popup style.
how?, pl help me.

**Comment by francocatena** [comment]
You can create your own template: https://github.com/francocatena/meteor-status#creating-a-custom-template

If you want some example take a look to the templates folder: https://github.com/francocatena/meteor-status/tree/master/templates

**Comment by yuomtheara** [comment]
Very thanks for your reply, I understand for custom normal style.
Pl example for popup style.

**Comment by francocatena** [comment]
I am not sure what you mean then. If you want a modal from Bootstrap for example, then you should go with the template aproach and create one.

On the other hand, if you only want an alert when the user lost his connection, then you should use plain Meteor and go with something like:

```javascript
Tracker.autorun(function () {
  var status = Meteor.connection.status()

  if (! status.connected)
    alert('Meteor ' + status.status)
})
```

Cheers.

**Comment by yuomtheara** [comment]
I would like to create custom with popup like `loading/wait spinner`.

**Comment by francocatena** [comment]
Then you need to do it with a custom template and something like: http://getbootstrap.com/javascript/#modals

**Comment by yuomtheara** [comment]
thanks.
